### ISSUE TITLE
This isshue came on whmcs 8.4 , can you resolve please..

### ISSUE THREAD

**Issue by utsaroy4** [NawabHost/bkash-checkout-for-whmcs#11]
![image](https://user-images.githubusercontent.com/49422403/169508940-a8cfa0cf-041c-4b74-871a-b46514b666f4.png)

**Comment by AminulBD** [comment]
Hi, thank you for your report, I'm assume that your site URL is incorrect. Do as image below.

![image](https://user-images.githubusercontent.com/5006546/169514126-61b489fc-5186-40c1-b2b4-38a32befef59.png)

And, Please don't forget to update me, what happened after applied this changes.

**Comment by utsaroy4** [comment]
thank you, man... I already fixed that issue. that was an SSL error of my server...

**Comment by AminulBD** [comment]
Glad know that your issue has been resolved.

**Comment by greenviewsoft** [comment]
Thanks For Replay Aminul vai now face this issue :  Invalid response from the bKash Server.

**Comment by AminulBD** [comment]
> Thanks For Replay Aminul vai now face this issue : Invalid response from the bKash Server.

@greenviewsoft it should be credential issue.

**Comment by greenviewsoft** [comment]
i double checked  credential  is okay,    stile issue : Invalid response from the bKash Server.


My WHMCS 8.2.1  Version

**Comment by AminulBD** [comment]
@greenviewsoft Please see https://github.com/NawabHost/bkash-tokenized-checkout-for-whmcs?tab=readme-ov-file#faqs
