### ISSUE TITLE
***The transaction already has been used*** #whmcs Bkash module issue

### ISSUE THREAD

**Issue by tanviralimon** [NawabHost/bkash-checkout-for-whmcs#12]
This is a severe issue, this issue made this module unusable, @AminulBD can you fix it?

![image](https://user-images.githubusercontent.com/54432546/174496114-b166670f-e010-4f46-b48f-d1aa9ddbb85a.png)

**Comment by AminulBD** [comment]
See #11

**Comment by AminulBD** [comment]
This module is perfectly working on your site. You are using the same transactions. Payment gateway must accept any transactions for once. Try with new payment.

**Comment by tanviralimon** [comment]
@AminulBD im facing this issue with every payment

**Comment by AminulBD** [comment]
Can you please let me know which version of WHMCS are you using and PHP version?

**Comment by AminulBD** [comment]
This issue is not related with our module. Please see your browser or other module.
