### ISSUE TITLE
Already setup Bkash Api but not working auto payment

### ISSUE THREAD

**Issue by suhagrana** [NawabHost/bkash-checkout-for-whmcs#15]
Unfortunately your payment attempt was not successful.
Please try again or contact support.

**Comment by AminulBD** [comment]
Can you describe it little bit more, what issue you are facing?

**Comment by mrmitnetwork** [comment]
I facing also this issue. I think it's a version compatibility issue. That's why this add-on need to update to make Compatible with WHMCS 8.6.1.

**Comment by AminulBD** [comment]
Please see our Pro version in the Readme.
