### ISSUE TITLE
Bkash payment gateway module 

### ISSUE THREAD

**Issue by dmcapbd** [NawabHost/bkash-checkout-for-whmcs#16]
Dear vai.
Bkash payment gateway whmcs module not working. Please solve it.

**Comment by AminulBD** [comment]
Please describer what error you are getting?

Aslo, please WHMCS Version, and PHP version write here.

**Comment by dmcapbd** [comment]
Whmcs Version 8.5
Show error: Invalid response from the bKash Server.

**Comment by AminulBD** [comment]
Please see this: https://github.com/NawabHost/bkash-checkout-for-whmcs/issues/11#issuecomment-1132766567
