### ISSUE TITLE
Invalid response from the bKash Server.

### ISSUE THREAD

**Issue by rana4u** [NawabHost/bkash-checkout-for-whmcs#19]
After putting all sandbox-credentials the cart checkout for WHMCS shows "Invalid response from bKash Server"

**Comment by newazfarhan** [comment]
I face the same issue and hope to fix it soon.

**Comment by abuhurayrait** [comment]
same problem

**Comment by viphostbd** [comment]
sandbox work . but I give same problem is Invalid response from the bKash Server. 
My whmcs version is  8.7.3. Please Give me solutions.

**Comment by zehadulislam** [comment]
invalid response from bkash server. is it bkash problem or your coding?

**Comment by AminulBD** [comment]
Please see this: Please see: https://github.com/NawabHost/bkash-checkout-for-whmcs/issues/11#issuecomment-1132766567
