### ISSUE TITLE
Module Not working

### ISSUE THREAD

**Issue by firozdotcode** [NawabHost/bkash-checkout-for-whmcs#2]
Dear Sir, It's not working. It's shows Unfortunately your payment attempt was not successful.
Please try again or contact support.
<img width="1280" alt="Screenshot 2021-06-17 at 12 00 45 AM" src="https://user-images.githubusercontent.com/26923664/122270576-4638a880-cf00-11eb-8f39-387bc973df73.png">

**Comment by AminulBD** [comment]
Thank you for your report.

Can you please give me some more information so I can proceed?

WHMCS Version:
PHP Version:
The theme that you are using.

**Comment by firozdotcode** [comment]
WHMCS Version: 8.1.0
PHP Version 7.3.28
System Theme: Twenty-One

**Comment by mdrana101** [comment]
Same Problem 
WHMCS 8.20
PHP 7.4

**Comment by AminulBD** [comment]
This issue can be happened if you entered invalid credential in the config area.

Please check!

**Comment by AminulBD** [comment]
See #7
