### ISSUE TITLE
Invalid response from the bKash Server.

### ISSUE THREAD

**Issue by mgmynul** [NawabHost/bkash-checkout-for-whmcs#20]
When try to make a payment by clicking the bKash logo image shows Invalid response from the bKash Server.

WHMCS version: 8.8.0
PHP version: 8.1

What I have to do?

![Screenshot_20230927-132521_Chrome](https://github.com/NawabHost/bkash-checkout-for-whmcs/assets/31184931/c7c1d94f-6b9b-4d87-8567-27b0c82ca2e1)

**Comment by AminulBD** [comment]
Please see this: https://github.com/NawabHost/bkash-checkout-for-whmcs/issues/11#issuecomment-1132766567

Let me know if that didn't helps.

Please make sure you have SSL.

**Comment by mgmynul** [comment]
All is ok (SSL, website URL) ... but not working

**Comment by mgmynul** [comment]
Any one there? Who will solved my problem..

**Comment by mgmynul** [comment]
I have emailed you with proper documentation and attachments

**Comment by AminulBD** [comment]
In above screenshot, I can see the URL is not same. the "Domain" field is missing forward slash`/`.

YOU MUST HAVE EXACT SAME URL IN BOTH FIELD.
