### ISSUE TITLE
Invalid response from the bKash Server.

### ISSUE THREAD

**Issue by samsusiyam** [NawabHost/bkash-checkout-for-whmcs#21]
I have SSL on my domain here you can see this:
https://prnt.sc/8pDU_wb-dPdi

The Problem: https://prnt.sc/Uq64XQ0OPa7n

PHP Version 7.4
WHMCS Version : 8.7.3

**Comment by AminulBD** [comment]
@samsusiyam Please make sure your php is allow `allow_url_fopen`. The value should be: `allow_url_fopen = On`
