### ISSUE TITLE
Callback url is accessible after logout.

### ISSUE THREAD

**Issue by ImSMostofa** [NawabHost/bkash-checkout-for-whmcs#3]
![image](https://user-images.githubusercontent.com/49339032/132346911-cb9d68cb-cc87-410e-8910-c0ebe833cb7b.png)

**Comment by AminulBD** [comment]
Hello there,

Thank you for using our module. bKash sometimes makes it difficult for people. But this is approved by bKash and is widely used in Bangladeshi hosting providers.

WHMCS doesn't have any way to prevent the file to access but you can write rules for .htaccess file or something else. But the file will not work or execute if the user has been logged out.

You can more see here: https://github.com/NawabHost/bkash-checkout-for-whmcs/blob/main/modules/gateways/callback/bkashcheckout.php#L442-L444

**Comment by ImSMostofa** [comment]
After many discussions, they understand this issue. Now they want bKash query API implementation data. This module can implement query API?
