### ISSUE TITLE
Should I add port 9081

### ISSUE THREAD

**Issue by azizulislam** [NawabHost/bkash-checkout-for-whmcs#5]
Hi,
I have a question is this module required to open port 9081 in the firewall?
Thanks for an awesome module.

**Comment by AminulBD** [comment]
This module implements the [Checkout](https://developer.bka.sh/reference) API. All API calls are utilizing the `443` port.

If you are looking for the legacy version of bKash module which is "transaction key based verification" then you can see that [here](https://github.com/NawabHost/bkash-merchant-for-whmcs).
