### ISSUE TITLE
Payment isnt working on https

### ISSUE THREAD

**Issue by ImSMostofa** [NawabHost/bkash-checkout-for-whmcs#6]
Many of us face an issue using this module. Which is **Unfortunately your payment attempt was not successful**. Today I try to find out the issue. This issue is not from bkash or any theme or others module.

All payment is working fine without SSL version and we get this error if your WHMCS domain or subdomain has SSL certificate installed. 

Im looks forward to it to @AminulBD Bhai. Hopefully, he will take a look into this issue. 

![image](https://user-images.githubusercontent.com/49339032/133996755-e56c469d-2505-4062-b7a1-cfdf80896f73.png)
![image](https://user-images.githubusercontent.com/49339032/133996835-cc4fe0eb-b805-4def-9f41-e8999db56891.png)

**Comment by mdrana101** [comment]
Same Problem.

**Comment by AminulBD** [comment]
@ImSMostofa do you have still same problem?

**Comment by AminulBD** [comment]
Can you please check your WHMCS System URL?

If you are using non-https then keep it non-https, if you are using https then, please use https and force redirect to https.

<img width="711" alt="image" src="https://user-images.githubusercontent.com/5006546/159198185-5bf3ee2c-0d31-4889-88f7-5062cf06fb3f.png">
