### ISSUE TITLE
Not Working Please Help

### ISSUE THREAD

**Issue by mdrana101** [NawabHost/bkash-checkout-for-whmcs#7]
WHMCS 8.20
PHP 7.4
![Capture](https://user-images.githubusercontent.com/26415536/139542039-30904ddf-9263-4900-be67-d37974c511cf.PNG)

**Comment by AminulBD** [comment]
Hi,

This issue can be happened if your server can't connect with bKash API or bKash API response with 4xx or 5xx http status.

You can now check:

- Check sandbox mode, If sandbox enabled, please use sandbox credential, If not then please use production credentials.
- Check `file_get_contents()` is working or not.
